NewsPaper/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('protect.urls')),
    path('admin/', admin.site.urls),
    path('news/', include('news.urls')),
    path('pages/', include('django.contrib.flatpages.urls')),
    path('sign/', include('sign.urls')),
    path('accounts/', include('allauth.urls')),
    path('appointments/', include(('appointment.urls', 'appointments'), namespace='appointments')),


]

appointment/urls.py
from django.urls import path,include
from .views import AppointmentView

app_name='appointments'
urlpatterns = [
    path('', AppointmentView.as_view(),name='make_appointment'),
]

news/urls.py
from django.urls import path

from .views import *


urlpatterns = [
   path('', PostList.as_view(),name='new_list'),
   path('<int:pk>', PostDetail.as_view(),name='new'),
   path('create/',PostCreate.as_view(),name='new_create'),
   path('<int:pk>/update/', PostUpdate.as_view(), name='new_update'),
   path('<int:pk>/delete/', PostDelete.as_view(), name='new_delete'),
   path('search/', PostSearch.as_view(), name='new_search'),
   path('articles/create/', PostCreate.as_view(), name='news_create'),
   path('articles/<int:pk>/edit', PostUpdate.as_view(), name='news_edit'),
   path('articles/<int:pk>/delete', PostDelete.as_view(), name='news_delete'),
   path('category/', CategoryList.as_view(), name='categories_list'),
   path('category/<int:pk>/subscribe', subscribe, name='subscribe'),
   path('category/<int:pk>/',CategoryDetail.as_view(),name='category'),
   path('category/<int:pk>/unsubscribe', unsubscribe, name='unsubscribe'),

]

news/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
import datetime



class Author(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    rating = models.IntegerField(default=0)

    def __str__(self):
        return self.user.username.title()

    def update_rating(self):
        article_rating = 0
        comment_rating = 0
        article_comment_rating = 0

        # Используем related_name для получения постов
        for post in self.posts.all():  # Теперь используем self.posts вместо self.post_set
            article_rating += post.rating * 3

        # Суммарный рейтинг всех комментариев автора
        for comment in Comment.objects.filter(user=self.user):
            comment_rating += comment.rating

        # Суммарный рейтинг всех комментариев к статьям автора
        for post in self.posts.all():  # Также здесь меняем на self.posts
            for comment in post.comments.all():  # И здесь на post.comments
                article_comment_rating += comment.rating

        # Обновляем рейтинг автора
        self.rating = article_rating + comment_rating + article_comment_rating
        self.save()


class Category(models.Model):
    name_category = models.CharField(max_length=60, unique=True)
    rating = models.IntegerField(default=0)
    date_in = models.DateTimeField(default=datetime.datetime.now)
    subscribers=models.ManyToManyField(User,related_name='subscribed_posts', blank=True)

    def __str__(self):
        return self.name_category.title()


class Post(models.Model):
    news = 'NW'
    article = 'AR'
    POST_TYPES = [
        (news, "Новость"),
        (article, "Статья")
    ]
    author = models.ForeignKey(Author, on_delete=models.CASCADE, related_name='posts')
    post_type = models.CharField(max_length=2, choices=POST_TYPES, default=news)
    date_in = models.DateTimeField(auto_now_add=True)
    category = models.ManyToManyField(Category, through='PostCategory')
    title = models.CharField(max_length=255)
    text = models.TextField()
    rating = models.IntegerField(default=0)

    def like(self):
        self.rating += 1
        self.save()

    def dislike(self):
        self.rating -= 1
        self.save()

    def preview(self):
        return self.text[0:255] + "..."

    def __str__(self):
        return f'{self.title.title()}: {self.text[:20]}'

    def get_absolute_url(self):
        return reverse('new', args=[str(self.id)])


class PostCategory(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.category.name_category.title()}: {self.post.title.title()}'


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.CharField(max_length=1000)
    date_in = models.DateTimeField(auto_now_add=True)
    rating = models.IntegerField(default=0)

    def like(self):
        self.rating += 1
        self.save()

    def dislike(self):
        self.rating -= 1
        self.save()


class Subscription(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    def __str__(self):
        return f"{self.user.username} subscribed to {self.category.name_category}"

news/forms.py
from django import forms
from django.core.exceptions import ValidationError

from .models import *


class PostForm(forms.ModelForm):
    title = forms.CharField(max_length=25)
    text = forms.CharField(max_length=200)

    class Meta:
        model = Post
        fields = [
            'author',
            'post_type',
            'rating',
            'title',
            'category',
            'text'
        ]

    def clean(self):
        cleaned_data = super().clean()
        post_text = cleaned_data.get("post_text")
        title = cleaned_data.get("title")

        if title == post_text:
            raise ValidationError(
                "Значение Title не должно быть таким же, как и Text."
            )

        return cleaned_data


class SubscriptionForm(forms.ModelForm):
    class Meta:
        model = Subscription
        fields = ['category']

news/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import PermissionRequiredMixin, LoginRequiredMixin
from django.core.mail import send_mail
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from .filters import *
from .forms import *
from django.contrib import messages
from django.conf import settings



class PostList(ListView):
    model = Post
    ordering = 'date_in'
    # template_name = 'news.html'
    context_object_name = 'news'
    queryset = Post.objects.order_by('-date_in')
    paginate_by = 2

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['list_in_page'] = self.paginate_by
        return context

    def get_queryset(self):
        queryset = super().get_queryset()
        self.filterset = PostFilter(self.request.GET, queryset)
        return self.filterset.qs

    def get_template_names(self):
        if self.request.path == '/news/create':
            return 'search.html'
        return 'news.html'


class PostDetail(DetailView):
    model = Post
    template_name = 'new.html'
    context_object_name = 'new'


class PostCreate(CreateView, PermissionRequiredMixin, LoginRequiredMixin):
    permission_required = ('news.add_post',)
    form_class = PostForm
    model = Post
    template_name = 'new_create.html'

    def form_valid(self, form):
        post = form.save(commit=False)
        if self.request.path == '/articles/create/':
            post.post_type = 'AR'
        post.save()
        return super().form_valid(form)


class PostUpdate(UpdateView, PermissionRequiredMixin, LoginRequiredMixin):
    permission_required = ('news.change_post',)
    form_class = PostForm
    model = Post
    template_name = 'new_create.html'


class PostDelete(DeleteView, PermissionRequiredMixin, LoginRequiredMixin):
    permission_required = ('news.delete_post',)
    model = Post
    template_name = 'new_delete.html'
    success_url = reverse_lazy('new_list')


class PostSearch(ListView):
    model = Post
    ordering = '-date_in'
    template_name = 'new_search.html'

    def get_queryset(self):
        queryset = super().get_queryset()
        self.filterset = PostFilter(self.request.GET, queryset)
        return self.filterset.qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['filterset'] = self.filterset
        return context


class CategoryList(ListView):
    model = Category
    template_name = 'categories_list.html'
    context_object_name = 'categories'


class CategoryDetail(DetailView):
    model = Category
    template_name = 'category.html'
    context_object_name = 'category'


# Рассылка уведомления на почту от подписке на категорию!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

# def subscribe(request, pk):
#     user = request.user
#     category = Category.objects.get(id=pk)
#
#     subscription, created = Subscription.objects.get_or_create(user=user, category=category)
#
#     if created:
#         send_mail(
#             'Подписка на категорию',
#             f'Вы успешно подписались на категорию {category.name_category}.',
#             settings.DEFAULT_FROM_EMAIL,
#             [user.email],
#             fail_silently=False,
#         )
#         messages.success(request, f'Вы успешно подписались на категорию {category.name_category}.')
#     else:
#         messages.warning(request, 'Вы уже подписаны на эту категорию.')
#
#     return redirect('category_detail', pk=pk)


@login_required
def subscribe(request, pk):
    user = request.user
    category = Category.objects.get(id=pk)
    category.subscribers.add(user)

    send_mail(
        'Подписка на категорию',
        f'Вы успешно подписались на категорию: {category.name_category}',
        settings.DEFAULT_FROM_EMAIL,
        [user.email],
        fail_silently=False,
    )

    messages.success(request, f'Вы успешно подписались на категорию: {category.name_category}')
    return redirect(f'/news/category/{category.pk}')


@login_required
def unsubscribe(request, pk):
    user = request.user
    category = Category.objects.get(id=pk)

    category.subscribers.remove(user)

    send_mail(
        'Отписка от категории',
        f'Вы успешно отписались от категории: {category.name_category}',
        settings.DEFAULT_FROM_EMAIL,
        [user.email],
        fail_silently=False,
    )

    messages.success(request, f'Вы успешно отписались от категории: {category.name_category}')
    return redirect(f'/news/category/{category.pk}')

# def send_weekly_post_notifications():
#     # Вычисляем дату, которая была неделю назад
#     today = timezone.now()
#     last_week = today - timezone.timedelta(days=7)
#
#     # Получаем все статьи, созданные за последнюю неделю
#     recent_posts = Post.objects.filter(date_in__gte=last_week)
#
#     # Собираем всех подписчиков
#     subscribers = set()
#     for post in recent_posts:
#         categories = post.category.all()
#         for category in categories:
#             subscribers.update(category.subscribers.all())
#
#     subject = 'Новые статьи за последнюю неделю'
#     from_email = settings.DEFAULT_FROM_EMAIL
#
#     for subscriber in subscribers:
#         message = render_to_string('account/email/week_post.html', {
#             'posts': recent_posts,
#             'base_url': settings.SITE_URL,
#             'user': subscriber
#         })
#         send_mail(subject=subject, message='', from_email=from_email, recipient_list=[subscriber.email],
#                   html_message=message)

# КОНЕЦ РАССЫЛКИ СООБЩЕНИЙ !!!!!!!!!!!!!!!!!!!!!!!!!!!!

templates/appointment_created.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h2>{{ appointment.client_name }} Спасибо за запись!</h2>
    <p> Вы записаны на {{ appointment.date|date:"d-M-Y" }} по вопросу: {{ appointment.message|truncatechars:50 }} </p>
</body>
</html>

templates/categories_list.html
{% extends 'flatpages/default.html' %}

{% load custom_filters %}
<!-- Подключаем новый файл с нашим тегом -->
{% load custom_tags %}

{% block title %}
Categories
{% endblock title %}

{% block content %}
<h1>Список категорий</h1>
<hr>

{% if categories %}
    {% for cat in categories %}
        <h3>{{ cat.name_category }}</h3>

        {% if user.is_authenticated %}
            {% if user in cat.subscribers.all %}
                <form action="{% url 'unsubscribe' cat.id %}" method="post">
                    {% csrf_token %}
                    <button type="submit">Отписаться от категории</button>
                </form>
            {% else %}
                <form action="{% url 'subscribe' cat.id %}" method="post">
                    {% csrf_token %}
                    <input type="submit" value="Подписаться">
                </form>
            {% endif %}
        {% endif %}
    {% endfor %}
{% else %}
    <p>Категории отсутствуют.</p>
{% endif %}
{% endblock content %}

templates/category.html
<!--  наследуемся от шаблона default.html, который мы создавали для flatpages -->
{% extends 'flatpages/default.html' %}

{% load custom_filters %}

{% block title %}
Category
{% endblock title %}

{% block content %}
<h1>Текущая категория</h1>
<hr>
{% if category %}
<dl>
    <dt>Название
    <dt>
    <dd>{{category.name_category|censor}}</dd>
    <dt>Дата публикации
    <dt>
    <dd>{{category.date_in|date:'M d Y'}}</dd>
    <dt>Рейтинг категории
    <dt>
    <dd>{{category.rating}}</dd>
</dl>
{% else %}
<h3>Такой категории нет!</h3>
{% endif %}
{% if messages %}
<ul>
    {% for message in messages %}
    <li>{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}
{% endblock content %}

templates/main.html
<html>
    <head>
        <title> Simple SignUp/SignIn app</title>
    </head>
    <body>
        <div>
            <h1><a href="/">Simple SignUp/SignIn app</a></h1>
        </div>
        {% block content %}
        {% endblock %}
    </body>
</html>

templates/make_appointment.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Make an Appointment</title>
</head>
<body>
    <h1>Make an Appointment</h1>
    <form action="{% url 'appointments:make_appointment' %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}

        <label for="client_name">Your name</label>
        <input type="text" name="client_name" id="client_name"><br>

        <label for="message">Short description of your issue</label>
        <input type="text" name="message" id="message"><br>

        <label for="date">Choose time</label>
        <input type="date" name="date" id="date"><br>

        <input type="submit" value="Submit">
    </form>
</body>
</html>

templates/new.html
<!--  наследуемся от шаблона default.html, который мы создавали для flatpages -->
{% extends 'flatpages/default.html' %}

{% load custom_filters %}

{% block title %}
New
{% endblock title %}

{% block content %}
    <h1>Текущая новость/статья</h1>
    <hr>
    {% if new %}
        <dl>
            <dt>Заголовок<dt>
            <dd>{{new.title|censor}}</dd>
            <dt>Дата публикации<dt>
            <dd>{{new.date_in|date:'M d Y'}}</dd>
            <dt>Текст статьи<dt>
            <dd>{{new.text|censor}}</dd>
        </dl>
    {% else %}
       <h3>Такого поста нет!</h3>
   {% endif %}
{% endblock content %}

templates/new_create.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1>Создать пост</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save" />
</form>
{% endblock content %}

templates/new_delete.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1>Удаление поста</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    <p>Удалить "{{object.title}}"?</p>
    <input type="submit" value="Delete" />
</form>
{% endblock content %}

templates/new_edit.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1>Товар</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save" />
</form>
{% endblock content %}

templates/new_search.html
{% extends 'flatpages/default.html' %}

{% load custom_filters %}
{% load custom_tags %}

{% block title %}
Поиск новостей
{% endblock title %}

{% block content %}
   <h1>Поиск:</h1>
   <form action="" method="get">
       {{ filterset.form.as_p }}
       <input type="submit" value="Найти" />
   </form>

   <hr>
   {% if filterset.qs %}
       <table>
           <tr>
               <td style="font-size: 16px; font-weight: bold;">Заголовок</td>
               <td style="font-size: 16px; font-weight: bold;">Дата публикации</td>
               <td style="font-size: 16px; font-weight: bold;">Превью</td>
           </tr>
           {% for post in filterset.qs %}
           <tr>
               <td>{{post.title|censor}}</td>
               <td>{{post.post_time_in|date:'M d Y'}}</td>
               <td>{{post.post_text|truncatechars:20|censor}}</td>
           </tr>
           {% endfor %}

       </table>
   {% else %}
       <h2>Здесь пока пусто.</h2>
   {% endif %}

   {% if page_obj.has_previous %}
       <a href="?{% url_replace page=1 %}">1</a>
       {% if page_obj.previous_page_number != 1 %}
           ...
           <a href="?{% url_replace page=page_obj.previous_page_number %}">{{ page_obj.previous_page_number }}</a>
       {% endif %}
   {% endif %}

   {{ page_obj.number }}

   {% if page_obj.has_next %}
       <a href="?{% url_replace page=page_obj.next_page_number %}">{{ page_obj.next_page_number }}</a>
       {% if paginator.num_pages != page_obj.next_page_number %}
           ...
           <a href="?{% url_replace page=page_obj.paginator.num_pages %}">{{ page_obj.paginator.num_pages }}</a>
       {% endif %}
   {% endif %}

{% endblock content %}

templates/news.html
{% extends 'flatpages/default.html' %}

{% load custom_filters %}
<!-- Подключаем новый файл с нашим тегом -->
{% load custom_tags %}

{% block title %}
News
{% endblock title %}

{% block content %}
   <h1>Новости на сегодня</h1>
   <h3>{% current_time '%b %d %Y' %}</h3>
    <form action="" method="get">
       {{ filterset.form.as_p }}
       <input type="submit" value="Найти" />
   </form>

    <style type="text/css">
  td {
    padding: 0 15px;
  }
    </style>

   <hr>
   {% if news %}
       <table>
           <tr>
               <td>Автор</td>
               <td>Тип</td>
               <td>Дата публикации</td>
               <td>Заголовок</td>
               <td>Текст</td>
               <td>Рейтинг</td>
           </tr>

           {% for new in news %}
           <tr>
               <td>{{ new.author }}</td>

               <td>{{ new.post_type }}</td>

               <td>{{ new.date_in }}</td>
               <td>{{ new.title }}</td>
               <td>{{ new.text|truncatechars:20 }}</td>
               <td>{{ new.rating }}</td>
           </tr>
           {% endfor %}

       </table>
   {% else %}
       <h2>Новостей нет!</h2>
   {% endif %}

    {% if page_obj.has_previous %}
           {# Для каждой ссылки пагинации указываем обработку через новый тег #}
           <a href="?{% url_replace page=1 %}">1</a>
           {% if page_obj.previous_page_number != 1 %}
               ...
               <a href="?{% url_replace page=page_obj.previous_page_number %}">{{ page_obj.previous_page_number }}</a>
           {% endif %}
       {% endif %}

       {{ page_obj.number }}

       {% if page_obj.has_next %}
           <a href="?{% url_replace page=page_obj.next_page_number %}">{{ page_obj.next_page_number }}</a>
           {% if paginator.num_pages != page_obj.next_page_number %}
               ...
               <a href="?{% url_replace page=page_obj.paginator.num_pages %}">{{ page_obj.paginator.num_pages }}</a>
           {% endif %}
       {% endif %}

    {% endblock content %}

templates/subscribe.html
<!--{% for category in categories %}-->
<!--<div>-->
<!--    {% if messages %}-->
<!--    {% for message in messages %}-->
<!--    <div class="{{ message.tags }}">{{ message }}</div>-->
<!--    {% endfor %}-->
<!--    {% endif %}-->
<!--    <h2>{{ category.name_category }}</h2>-->
<!--    <form action="{% url 'subscribe' category.id %}" method="post">-->
<!--        {% csrf_token %}-->
<!--        <button type="submit">Подписаться на эту категорию</button>-->
<!--    </form>-->
<!--</div>-->
<!--{% endfor %}-->